# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='made before the textfield was created'),
            preserve_default=False,
        ),
    ]
